"""Generic prompt-eval harness.

You do NOT edit this file to add a new eval. You write one eval module (see
implementor_eval.py) that fills in an `EvalSpec` describing what your prompt
needs, then call `run_eval(spec)`. This file owns the parts every eval shares:
the sandbox, the opencode invocation, artifact writing, the loop, and the
pass/fail summary.

An eval is defined by six phases — each a small function in your eval module:

    setup(repo)            -> state    build the sandbox repo, return whatever
                                       gather will need (e.g. the base commit)
    render(prompt_data)    -> str      turn a test case into the prompt text
    gather(repo, state, stdout) -> facts   observe the result (no judgement)
    checks                 : list[Check]   pure predicates over the facts
    build_report(prompt_data, facts, results) -> dict   (optional) shape result.json
    prepare()                          (optional) one-time host setup

A test case is one line in the prompts JSONL — no code change needed.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from config import ARTIFACTS, MODEL


def run(*args: str, cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    """Run a subprocess with a clean env (no inherited virtualenv)."""
    env = os.environ.copy()
    env.pop("VIRTUAL_ENV", None)
    return subprocess.run(list(args), cwd=cwd, env=env, check=check, text=True, capture_output=True)


@dataclass
class EvalContext:
    """What a check is allowed to look at: observed facts + the test case."""

    facts: Any
    prompt: dict


@dataclass
class Check:
    name: str
    description: str
    run: Callable[[EvalContext], bool]


def evaluate(ctx: EvalContext, checks: list[Check]) -> dict[str, bool]:
    """Run every check, returning {check_name: passed}."""
    return {check.name: check.run(ctx) for check in checks}


def _default_report(prompt_data: dict, facts: Any, results: dict[str, bool]) -> dict:
    return dict(results)


@dataclass
class EvalSpec:
    """Everything that makes one eval different from another."""

    name: str
    prompts_path: Path
    agent_prompt: Path  # the .md attached to opencode via --file
    setup: Callable[[Path], Any]
    render: Callable[[dict], str]
    gather: Callable[[Path, Any, str], Any]
    checks: list[Check]
    build_report: Callable[[dict, Any, dict[str, bool]], dict] = _default_report
    prepare: Callable[[], None] = lambda: None


def load_prompts(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def run_opencode(repo: Path, prompt: str, agent_prompt: Path) -> subprocess.CompletedProcess[str]:
    return run(
        "opencode",
        "run",
        prompt,
        "--format",
        "json",
        "--model",
        MODEL,
        "--dangerously-skip-permissions",
        f"--file={agent_prompt}",
        cwd=repo,
        check=False,
    )


def eval_passed(report: dict, checks: list[Check]) -> bool:
    """A run passes only if opencode ran and every check is True."""
    if report.get("opencode_failed"):
        return False
    return all(report.get(check.name) for check in checks)


def _run_one(spec: EvalSpec, prompt_data: dict) -> dict:
    pid = prompt_data["id"]
    sandbox = Path(tempfile.mkdtemp(prefix=f"{spec.name}-eval-{pid}-"))
    repo = sandbox / "repo"
    try:
        state = spec.setup(repo)
        prompt = spec.render(prompt_data)
        result = run_opencode(repo, prompt, spec.agent_prompt)
        (ARTIFACTS / f"{pid}.jsonl").write_text(result.stdout, encoding="utf-8")
        (ARTIFACTS / f"{pid}.stderr.txt").write_text(result.stderr, encoding="utf-8")
        if result.returncode != 0:
            return {
                "id": pid,
                "opencode_failed": True,
                "returncode": result.returncode,
                "stderr_tail": result.stderr[-2000:],
            }
        facts = spec.gather(repo, state, result.stdout)
        ctx = EvalContext(facts=facts, prompt=prompt_data)
        results = evaluate(ctx, spec.checks)
        report = {"id": pid, **spec.build_report(prompt_data, facts, results)}
        return report
    finally:
        shutil.rmtree(sandbox, ignore_errors=True)


def run_eval(spec: EvalSpec) -> int:
    ARTIFACTS.mkdir(parents=True, exist_ok=True)
    spec.prepare()
    prompts = load_prompts(spec.prompts_path)

    results: list[dict] = []
    for prompt_data in prompts:
        pid = prompt_data["id"]
        print(f"=== {pid} ===", flush=True)
        report = _run_one(spec, prompt_data)
        (ARTIFACTS / f"{pid}.result.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        results.append(report)
        printable = {k: v for k, v in report.items() if k not in {"pytest_stdout", "pytest_stderr"}}
        print(json.dumps(printable, indent=2), flush=True)

    summary = {
        "total": len(results),
        "passed": sum(1 for r in results if eval_passed(r, spec.checks)),
        "results": results,
    }
    (ARTIFACTS / f"{spec.name}-summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps({"total": summary["total"], "passed": summary["passed"]}, indent=2))
    return 0 if summary["passed"] == summary["total"] else 1
